/// Flutter icons GvChat
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GvChat
///      fonts:
///       - asset: fonts/GvChat.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData google = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData eye_hide = IconData(0xe801, fontFamily: _kFontFam);
}
